inherit_gem:
  rubocop-rails-omakase: rubocop.yml

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  CacheRootDirectory: /workspace/.rubocop-cache
  Exclude:
    - ".ruby-local/**/*"
    - "vendor/**/*"
